services:
  spring-boot-microservice:
    container_name: spring_boot_microservice
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Application port
      - "8081:8081" # Management port
    restart: always
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
        - monitoring
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus
    depends_on:
      - spring-boot-microservice
    command: --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
        - monitoring
    ports:
      - "3000:3000"
    restart: always
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

networks:
    monitoring:
        driver: bridge
        name: spring_boot_microservice_monitoring

volumes:
  prometheus-data:
  grafana-data: