spring:
  main:
    lazy-initialization: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  configure:
    include:
#      - com.org.microservice.config.OpenApiConfig
      - com.org.microservice.documents.controller.**
      - com.org.microservice.documents.model.**
    exclude:
      - com.org.microservice.documents.**
    optional:
      - com.org.microservice.documents.**