global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090'] # Scrape Prometheus
  - job_name: 'microservice'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'spring-boot-microservice:8081' # Scrape Spring Boot Actuator of the microservice
# Since both Prometheus and the Spring Boot application are running in Docker containers, utilise the service name defined in docker-compose.yml instead of localhost